server:
  port: 80


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
      location: /temp/upload
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml


wechat:
  app-id: wxa840921ec0f3778e
  app-secret:  79989e84a65e55947148777e49654d26